BookStoreOnion/Models/AuthorViewModel.cs
using Microsoft.AspNetCore.Mvc;
using OA.Data;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookStoreOnion.Models
{
    public class AuthorViewModel
    {
        [HiddenInput]
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Address { get; set; }
        [NotMapped]
        public IFormFile? AuthorImage { get; set; }
        public string? AuthorImageUrl { get; set; }

        public virtual ICollection<Book>? Books { get; set; }
    }
}

BookStoreOnion/Controllers/AuthorController.cs
using BookStoreOnion.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OA.Data;
using OA.Service;

namespace BookStoreOnion.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IBookService bookService;
        private readonly IAuthorService authorService;
        private IWebHostEnvironment Environment;
        public AuthorController(IBookService bookService, IAuthorService authorService, IWebHostEnvironment _environment)
        {
            this.bookService = bookService;
            this.authorService = authorService;
            Environment = _environment;
        }
        public IActionResult Index()
        {
            List<AuthorViewModel> model = new List<AuthorViewModel>();
            authorService.GetAuthors().ToList().ForEach(a =>
            {
                Author authorDetails = authorService.GetAuthor(a.Id);
                AuthorViewModel author = new AuthorViewModel
                {
                    Id = a.Id,
                    Name = a.Name,
                    Address = a.Address,
                    AuthorImageUrl = a.AuthorImageUrl,
                };
                model.Add(author);
            });
            return View(model);
        }


        // GET: Author/Details/5
        public IActionResult Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var getId = id;

            var a = authorService.GetAuthor(id);
            var books = bookService.GetBooksByAuthor(id);

            AuthorViewModel author = new AuthorViewModel
            {
                Id = a.Id,
                Name = a.Name,
                Address = a.Address,
                AuthorImageUrl = a.AuthorImageUrl,
                Books = books.ToList(),
            };
            //ViewBag.books = books;

            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }


        // GET: Author/Create
        public IActionResult Create()
        {
            var model = new AuthorViewModel();
            return View(model);
        }


        // POST: Author/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(AuthorViewModel model)
        {
            //var author = authorService.GetAuthor(model.Id);

            if (ModelState.IsValid)
            {
                var new_author = new Author
                {
                    Name = model.Name,
                    Address = model.Address,
                    AuthorImageUrl = model.AuthorImageUrl,
                };

                if (model.AuthorImage != null && model.AuthorImage.Length > 0)
                {
                    var date = DateTime.Now.ToString("yyyyMMddHHmmss");
                    var fileName = date + Path.GetFileName(model.AuthorImage.FileName);
                    var filePath = Path.Combine(Environment.WebRootPath, "images", fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        model.AuthorImage.CopyTo(fileStream);
                    }
                    new_author.AuthorImageUrl = "/images/" + fileName;
                }

                authorService.InsertAuthor(new_author);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }


        // GET: Author/Edit/5
        public IActionResult Edit(int id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var author = authorService.GetAuthor(id);


            if (author == null)
            {
                return NotFound();
            }

            AuthorViewModel edited_author = new AuthorViewModel
            {
                Id = author.Id,
                Name = author.Name,
                Address = author.Address,
                AuthorImageUrl = author.AuthorImageUrl,
            };

            return View(edited_author);

            // set the Authors property to a SelectList containing all authors
            //return View(book);
        }


        // POST: Author/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, AuthorViewModel model)
        {

            if (id == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {

                var author = authorService.GetAuthor(id);


                if (author == null)
                {
                    return NotFound();
                }


                author.Id = model.Id;
                author.Name = model.Name;
                author.Address = model.Address;
                //author.AuthorImageUrl = model.BookImageUrl;

                authorService.UpdateAuthor(author);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }


        // GET: Author/Delete/5
        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = authorService.GetAuthor(id);
            var books = bookService.GetBooksByAuthor(id);
            if (author == null)
            {
                return NotFound();
            }

            AuthorViewModel deleting_author = new AuthorViewModel
            {
                Id = author.Id,
                Name = author.Name,
                Address = author.Address,
                Books = books.ToList(),
            };

            return View(deleting_author);
        }

        // POST: Author/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (authorService.GetAuthors().ToList() == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Books'  is null.");
            }
            var author = authorService.GetAuthor(id);
            if (author != null)
            {
                authorService.DeleteAuthor(id);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

BookStoreOnion/Controllers/BookController.cs
using BookStoreOnion.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;
using Microsoft.EntityFrameworkCore;
using OA.Data;
using OA.Service;

namespace BookStoreOnion.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService bookService;
        private readonly IAuthorService authorService;
        private IWebHostEnvironment Environment;
        public BookController(IBookService bookService, IAuthorService authorService, IWebHostEnvironment _environment)
        {
            this.bookService = bookService;
            this.authorService = authorService;
            Environment = _environment;
        }



        // GET: Books
        [HttpGet]
        public IActionResult Index()
        {
            List<BookViewModel> model = new List<BookViewModel>();
            bookService.GetBooks().ToList().ForEach(b =>
            {
                Book bookDetails = bookService.GetBook(b.Id);
                BookViewModel book = new BookViewModel
                {
                    Id = b.Id,
                    Title = b.Title,
                    Language = b.Language,
                    BookImageUrl = b.BookImageUrl,
                    Author = authorService.GetAuthor(b.AuthorId),
                };
                model.Add(book);
            });
            return View(model);
        }


        // GET: Books/Details/5
        public IActionResult Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var b = bookService.GetBook(id);
            BookViewModel book = new BookViewModel
            {
                Id = b.Id,
                Title = b.Title,
                Language = b.Language,
                BookImageUrl = b.BookImageUrl,
                Author = authorService.GetAuthor(b.AuthorId),
            };
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            var authors = authorService.GetAuthors().ToList();


            var model = new BookViewModel();

            // set the Authors property to a SelectList containing all authors
            ViewBag.Authors = new SelectList(authors, "Id", "Name");

            return View(model);
        }




        // POST: Books/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BookViewModel model)
        {
            var author = authorService.GetAuthor(model.Id);

            if (ModelState.IsValid)
            {
                var new_book = new Book
                {
                    Title = model.Title,
                    Language = model.Language,
                    Author = model.Author,
                    AuthorId = model.AuthorId,
                };

                if (model.BookImage != null && model.BookImage.Length > 0)
                {
                    var date = DateTime.Now.ToString("yyyyMMddHHmmss");
                    var fileName = date + Path.GetFileName(model.BookImage.FileName);
                    var filePath = Path.Combine(Environment.WebRootPath, "images", fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        model.BookImage.CopyTo(fileStream);
                    }
                    new_book.BookImageUrl = "/images/" + fileName;
                }

                bookService.InsertBook(new_book);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Books/Edit/5
        public IActionResult Edit(int id)
        {
            var authors = authorService.GetAuthors().ToList();

            if (id == null)
            {
                return NotFound();
            }

            var book = bookService.GetBook(id);


            if (book == null)
            {
                return NotFound();
            }

            BookViewModel edited_book = new BookViewModel
            {
                Id = book.Id,
                Title = book.Title,
                Language = book.Language,
                BookImageUrl = book.BookImageUrl,
                Author = authorService.GetAuthor(book.AuthorId),
            };

            ViewBag.Authors = new SelectList(authors, "Id", "Name");
            return View(edited_book);

            // set the Authors property to a SelectList containing all authors
            //return View(book);
        }


        // POST: Books/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, BookViewModel model)
        {
            var authors = authorService.GetAuthors().ToList();

            if (id == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {

                var book = bookService.GetBook(id);


                if (book == null)
                {
                    return NotFound();
                }


                book.Id = model.Id;
                book.Title = model.Title;
                book.Language = model.Language;
                //book.BookImageUrl = model.BookImageUrl;
                book.Author = authorService.GetAuthor(model.AuthorId);

                bookService.UpdateBook(book);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Books/Delete/5
        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book =  bookService.GetBook(id);
            if (book == null)
            {
                return NotFound();
            }

            BookViewModel deleting_book = new BookViewModel
            {
                Id = book.Id,
                Title = book.Title,
                Language = book.Language,
                BookImageUrl = book.BookImageUrl,
                Author = authorService.GetAuthor(book.AuthorId),
            };

            return View(deleting_book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id, BookViewModel model)
        {
            if (bookService.GetBooks().ToList() == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Books'  is null.");
            }
            var book =  bookService.GetBook(id);
            if (book != null)
            {
                bookService.DeleteBook(id);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

BookStoreOnion/Views/Author/Create.cshtml
@model BookStoreOnion.Models.AuthorViewModel

@{
    ViewData["Title"] = "Create";
}


<h3 class="center">Add Author</h3>

<div class="row">
    <div class="form">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" ></div>

            <label asp-for="Name" ></label>
            <input asp-for="Name"  />
            <span asp-validation-for="Name"></span>

            <label asp-for="Address" ></label>
            <input asp-for="Address"  />
            <span asp-validation-for="Address" ></span>

            <label asp-for="AuthorImage" ></label>
            <input asp-for="AuthorImage" >
            <span asp-validation-for="Address" ></span>

            <input type="submit" value="Save"  />
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BookStoreOnion/Views/Author/Delete.cshtml
@model BookStoreOnion.Models.AuthorViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete an Author</h1>

<h3>Are you sure you want to delete this?</h3>

<div class="row">
    <div style="float: left">
        <div class="image">
            <img src="@Model.AuthorImageUrl" alt="Book Cover Image" height="300px">
        </div>
    </div>
    <div style="float: left">
        <div class="details">
            <p><b>Author Name:</b> @Html.DisplayFor(model => model.Name)</p>

            <p><b>Author Location:</b>@Html.DisplayFor(model => model.Address)</p>

            <p><b>Author Books:</b></p>
            <ul>
                @foreach (var book in Model.Books)
                {
                    <li><a asp-controller="Book" asp-action="Details" asp-route-id="@book.Id">@book.Title</a></li>
                }
            </ul>
        </div>
    </div>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn delete-btn" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>


<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AuthorImage)
        </dt>
        <dd class="col-sm-10">
            <img src="@Model.AuthorImageUrl" alt="Book Cover Image" height="150">
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        
    </dl>
    
    
</div>

BookStoreOnion/Views/Author/Details.cshtml
@model BookStoreOnion.Models.AuthorViewModel

@{
    ViewData["Title"] = "Author Details";
}

<h3>Author Details</h3>


<div class="row">
    <div style="float: left">
        <div class="image">
            <img src="@Model.AuthorImageUrl" alt="Book Cover Image" height="300px">
        </div>
    </div>
    <div style="float: left">
        <div class="details">
            <p><b>Author Name:</b> @Html.DisplayFor(model => model.Name)</p>

            <p><b>Author Location:</b>@Html.DisplayFor(model => model.Address)</p>

            <p><b>Author Books:</b></p>
            <ul>
                @foreach (var book in Model.Books)
                {
                    <li><a asp-controller="Book" asp-action="Details" asp-route-id="@book.Id">@book.Title</a></li>
                }
            </ul>
        </div>
    </div>
</div>


<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BookStoreOnion/Views/Author/Edit.cshtml
@model BookStoreOnion.Models.AuthorViewModel

@{
    ViewData["Title"] = "Edit";
}

<h3 class="center">Edit Author</h3>

<div class="row">
    <div class="form">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" ></div>
            <input type="hidden" asp-for="Id" />
            
            <label asp-for="Name"></label>
            <input asp-for="Name" />
            <span asp-validation-for="Name"></span>
            
            <label asp-for="Address"></label>
            <input asp-for="Address" />
            <span asp-validation-for="Address"></span>
            
            <input type="submit" value="Save" />
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BookStoreOnion/Views/Author/Index.cshtml
@model IEnumerable<BookStoreOnion.Models.AuthorViewModel>

@{
    ViewData["Title"] = "Index";
}

<div class="center">
    <h3>List of Authors</h3>
    <a class="button add-btn" asp-action="Create">Add New Author</a>
</div>


<div>
    @foreach (var item in Model)
    {
        <div class="row">
            <div class="columnAuth">
                @Html.DisplayFor(modelItem => item.Name)
            </div>
            <div class="columnAuth">
                @Html.DisplayFor(modelItem => item.Address)
            </div>
            <div class="columnAuth">
                <img src="@item.AuthorImageUrl" alt="Author Image" height="150">
            </div>
            <div class="columnAuth">
                <a class="btn edit-btn" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                <a class="btn details-btn" asp-action="Details" asp-route-id="@item.Id">Details</a>
                <a class="btn delete-btn" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </div>
        </div>
    }
</div>